# User schemas
from app.schemas.user import (
    UserBase,
    UserRegister,
    UserLogin,
    Token,
    TokenRefresh,
    UserUpdate,
    UserResponse,
    UserBrief,
    DriverResponse,
    FleetOperatorResponse,
)

# Vehicle schemas
from app.schemas.vehicle import (
    LocationUpdate,
    LocationResponse,
    VehicleBase,
    VehicleCreate,
    VehicleUpdate,
    VehicleResponse,
    VehicleBrief,
    LoadCapacityUpdate,
    CapacityResponse,
    FleetStats,
)

# Mission schemas
from app.schemas.mission import (
    GeoPoint,
    WaypointCreate,
    WaypointResponse,
    RouteData,
    FareBreakdown,
    ETARange,
    RiskFactor,
    RiskAssessment,
    AgentConfig,
    MissionCreate,
    MissionUpdate,
    MissionResponse,
    MissionBrief,
    MissionPlanRequest,
    MissionPlanResponse,
)

# Load schemas
from app.schemas.load import (
    LoadBase,
    LoadCreate,
    LoadUpdate,
    LoadResponse,
    LoadBrief,
    LoadSearchParams,
    LoadMatchRequest,
    LoadMatchResponse,
    BackhaulSuggestion,
    BackhaulSearchRequest,
    BackhaulSearchResponse,
)

# Decision schemas
from app.schemas.decision import (
    CostBenefit,
    Opportunity,
    ProposedChanges,
    DecisionCreate,
    DecisionResponse,
    DecisionBrief,
    DecisionAccept,
    DecisionReject,
    AgentAlert,
    MissionDecisionHistory,
    AgentMetrics,
)

# Checkpoint schemas
from app.schemas.checkpoint import (
    TollCharges,
    AvgDelays,
    OperatingHours,
    NoEntryTimings,
    Amenities,
    CheckpointCreate,
    CheckpointUpdate,
    CheckpointResponse,
    CheckpointBrief,
    CheckpointSearchParams,
    RouteCheckpoint,
    RouteCheckpointAnalysis,
    DelayEstimateRequest,
    DelayEstimateResponse,
)

__all__ = [
    # User
    "UserBase",
    "UserRegister",
    "UserLogin",
    "Token",
    "TokenRefresh",
    "UserUpdate",
    "UserResponse",
    "UserBrief",
    "DriverResponse",
    "FleetOperatorResponse",
    # Vehicle
    "LocationUpdate",
    "LocationResponse",
    "VehicleBase",
    "VehicleCreate",
    "VehicleUpdate",
    "VehicleResponse",
    "VehicleBrief",
    "LoadCapacityUpdate",
    "CapacityResponse",
    "FleetStats",
    # Mission
    "GeoPoint",
    "WaypointCreate",
    "WaypointResponse",
    "RouteData",
    "FareBreakdown",
    "ETARange",
    "RiskFactor",
    "RiskAssessment",
    "AgentConfig",
    "MissionCreate",
    "MissionUpdate",
    "MissionResponse",
    "MissionBrief",
    "MissionPlanRequest",
    "MissionPlanResponse",
    # Load
    "LoadBase",
    "LoadCreate",
    "LoadUpdate",
    "LoadResponse",
    "LoadBrief",
    "LoadSearchParams",
    "LoadMatchRequest",
    "LoadMatchResponse",
    "BackhaulSuggestion",
    "BackhaulSearchRequest",
    "BackhaulSearchResponse",
    # Decision
    "CostBenefit",
    "Opportunity",
    "ProposedChanges",
    "DecisionCreate",
    "DecisionResponse",
    "DecisionBrief",
    "DecisionAccept",
    "DecisionReject",
    "AgentAlert",
    "MissionDecisionHistory",
    "AgentMetrics",
    # Checkpoint
    "TollCharges",
    "AvgDelays",
    "OperatingHours",
    "NoEntryTimings",
    "Amenities",
    "CheckpointCreate",
    "CheckpointUpdate",
    "CheckpointResponse",
    "CheckpointBrief",
    "CheckpointSearchParams",
    "RouteCheckpoint",
    "RouteCheckpointAnalysis",
    "DelayEstimateRequest",
    "DelayEstimateResponse",
]
